<a href="https://colab.research.google.com/github/Aashish10571/Ml_Training/blob/main/Introduction/numpy_first_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to NumPy

what we will cover?

*   creating single dimensional arrays 👍
*   Multidimensional array 👍
*   Randomlyy generated array
*   Element wise operations
*   Summarizing operations

### Single dimensional arrays

In [1]:
import numpy as np

In [3]:
# create an array withh all the elements to be zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
# create an array with all the elememnts to be ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
# create an array of size 10 with all elements 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [6]:
# create an array of with different elements
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [7]:
# create an array starting with 3 and ending with 9
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
# create an array with evenly spaced numbers within a specified range
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multi Dimensional Array

In [11]:
# creating two dimensional array with all 0
np.zeros([3, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
# creating an square matrix with all elements 1
np.ones([3, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
# creating an square array with elements from 1 t0 9
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [23]:
a[0, 1] = 20
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [24]:
a[2] = [1, 1, 1]
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [26]:
a[:, 2] = [2, 2, 2]
a

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [27]:
# create an multidimensional array with all elements 10
np.full((3, 3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### Randomly Generated Arrays


*   NumPy can create arrays filled with random numbers
*   To ensure the reproducibility, you can set a seed using  ```np.random.seed()```.It will generate the exact same random numbers for each executions.
*   If you change the seed value, the sequence of random numbers will be changed

In [28]:
np.random.rand(5)

array([0.83542957, 0.08092165, 0.09645266, 0.35780641, 0.36598053])

In [29]:
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [30]:
np.random.randn(5, 2)

array([[-1.03446493,  0.66424004],
       [-1.13937438, -0.89472205],
       [-0.2207972 , -0.43007258],
       [ 1.19972246,  0.1222967 ],
       [ 0.54794733, -0.52658091]])

In [32]:
np.random.randint(low=0, high=100, size=(3, 3))

array([[69, 96, 56],
       [15,  3, 94],
       [39, 51, 94]])